# Site Info
title:              "Archidemus | Cosas Informáticas"
description:        "Comparto lo que aprendo para que no se me olvide"
google_analytics:   UA-102495783-1 # Put your Google Analytics code

# Author Info
author_name:        "Archidemus" # Your name here
author_email:       inorambuenaa@gmail.com # Your email here
author_gravatar:    3911aa470bacd82d3ab1d9ccbe11d2b8 # Your Gravatar md5 hash here for logo
twitter_username:   archidemus # Your Twitter username here
github_username:    archidemus # Your GitHub username here

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /:categories/:title # Post permalink
timezone:           America/Santiago # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to false to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
